name: Run Serial GPAW Tests

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Setup conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
        environment-name: run_tests
        init-shell: >-
          bash
          powershell
        cache-environment: false
        post-cleanup: 'all'
        create-args: >-
          python=${{ matrix.python-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies and build
      run: |
        sudo apt-get -qq install gcc cmake
    - name: Build things
      run: |
        source .github/workflows/load_conda.sh
        source .github/workflows/mm_install_torch.sh
        export CMAKE_CONFIGURE_ARGS="-DBUILD_WITH_MKL=ON -DBUILD_LIBXC=OFF"
        ./.github/workflows/run_local_pip.sh
        python scripts/download_functionals.py
    - name: Test with unittest
      run: |
        source .github/workflows/load_conda.sh
        ./.github/workflows/setup_gpaw_nompi.sh
        ./.github/workflows/run_gpaw_tests.sh
