name: Run MPI Tests BLAS

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and Test
        run: ./.github/workflows/run_gpaw_mpi_ci.sh
      - name: Run MPI tests
        run: |
          # Slightly hacky, link gpaw to our internal libxc
          export CIDER_DEPS=$(python -c "import ciderpress, os; print(os.path.dirname(ciderpress.__file__))")/lib/deps
          export LIBRARY_PATH=$LIBRARY_PATH:$CIDER_DEPS/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CIDER_DEPS/lib
          export C_INCLUDE_PATH=$C_INCLUDE_PATH:$CIDER_DEPS/include
          ./.github/workflows/run_mpi_tests.sh
