name: Publish

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  release-pypi-sdist:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ciderpress
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Build sdist
        run: |
          pip install build
          python3 -m build -s
      - name: List available sdist
        run: |
          ls ${{ github.workspace }}/dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
